services:
  mongo:
    image: mongo:6.0
    container_name: mutrapro-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/mutrapro_payment
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  studio-service:
    build: ./studio-service
    container_name: studio-service
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/mutrapro_studio
      PORT: 4100
    ports:
      - "4100:4100"
    depends_on:
      - mongo

volumes:
  mongo_data:
